### ISSUE TITLE
Better version handling

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#110]
I released a new version of Shazam intended for only 8.7 and higher (as stated in the compatibility block of config.json.

When the user installed it, it threw an error:

```
I tried to upgrade to Shazam v1.2.1 and it gave me an error:

An error occurred while enabling the module: <div class='red' style='max-width:700px;'>
							<b>ERROR:</b> There is an error in the REDCap plugin that you are currently using. Please contact
	this plugin's developer and send them the error info listed below so that they may fix this issue.
	If you do not know who the developer is for this plugin, then notify your REDCap administrator about this issue.<br><br>
							<b>Error message:</b> Uncaught Error: Call to undefined function ExternalModules\isCompatibleFormatCorrect() in /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php:1487
Stack trace:
#0 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php(517): ExternalModules\ExternalModules::isCompatibleWithREDCapPHP('shazam', 'v1.2.1')
#1 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php(562): ExternalModules\ExternalModules::enableForProject('shazam', 'v1.2.1', NULL)
#2 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php(568): ExternalModules\ExternalModules::enable('shazam', 'v1.2.1')
#3 /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/manager/ajax/enable-module.php(44): ExternalModules\ExternalModules::enableAndCatchExceptions('shazam', 'v1.2.1')
#4 {main}
  thrown <br>
							<b>File:</b> /dpool02/home/redcap/redcap/redcap_v8.6.5/ExternalModules/classes/ExternalModules.php <br>
							<b>Line:</b> 1487
						</div>
```
Wondering if this shouldn't be handled more gracefully in the EM class...

**Comment by mmcev106** [comment]
This has since been fixed.  I believe this error only previously occurred when the min version requirement was not met (so the min version was effective, even though the error didn't make any sense).  If you see any issues after 8.7.1, let me know.
