### ISSUE TITLE
Can't upload file at system setting level with "repeatable" flag enabled

### ISSUE THREAD

**Issue by eaneuhaus** [vanderbilt/redcap-external-modules#171]
I added a "file" field to my module's system level config and set "repeatable" to "true". When I choose a file and click "Save and Upload", it displays the following error:

```
undefined One or more of the files could not be saved."<br />\n<b>Fatal error</b>:  Uncaught Exception: The Project Id cannot be null! in /var/www/html/redcap_v8.11.3/ExternalModules/classes/ExternalModules.php:1167\nStack trace:\n#0 /var/www/html/redcap_v8.11.3/ExternalModules/manager/ajax/save-file.php(87): ExternalModules\\ExternalModules::getProjectSetting('quick_projects', NULL, 'xml-templates')\n#1 {main}\n  thrown in <b>/var/www/html/redcap_v8.11.3/ExternalModules/classes/ExternalModules.php</b> on line <b>1167</b><br />\n\t\t\t\t<div class=\"red\" style=\"margin:20px 0px;max-width:700px;\">\r\n\t\t\t\t\t<b>REDCap crashed due to an unexpected PHP fatal error!</b><br><br>\r\n\t\t\t\t\t<b>Error message:</b> Uncaught Exception: The Project Id cannot be null! in /var/www/html/redcap_v8.11.3/ExternalModules/classes/ExternalModules.php:1167\nStack trace:\n#0 /var/www/html/redcap_v8.11.3/ExternalModules/manager/ajax/save-file.php(87): ExternalModules\\ExternalModules::getProjectSetting('quick_projects', NULL, 'xml-templates')\n#1 {main}\n  thrown<br>\r\n\t\t\t\t\t<b>File:</b> /var/www/html/redcap_v8.11.3/ExternalModules/classes/ExternalModules.php<br>\r\n\t\t\t\t\t<b>Line:</b> 1167<br>\r\n\t\t\t\t</div>\r\n\t\t\t\t"
```

**Comment by mmcev106** [comment]
This definitely looks like a bug in the framework.  I am not sure when I'll be able to look into it just yet.  If you would like to look into it sooner, pull requests are always welcome.
