### ISSUE TITLE
Error specifying module to delete

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#175]
This issue was submitted to Shazam's github, but looks to be an EM issue:

user: skbiostat

```
REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught exception 'Exception' with message 'You must specify a module to delete!' in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\classes\ExternalModules.php:2598 Stack trace: #0 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\classes\ExternalModules.php(2533): ExternalModules\ExternalModules::deleteModuleDirectory(false, true) #1 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\manager\ajax\download-module.php(4): ExternalModules\ExternalModules::downloadModule('279', false, true) #2 {main} thrown
File: C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\classes\ExternalModules.php
Line: 2598
```

**Comment by mmcev106** [comment]
I did a quick review of the two `deleteModuleDirectory()` calls, but I'm not seeing an obvious case where `$moduleFolderName` parameter could be null/empty under normal conditions.  This may need to be debugged a bit from the server where it's taking place.

**Comment by mmcev106** [comment]
I'll close this since it hasn't been updated in a long time.  Feel free to reopen.
