### ISSUE TITLE
bug with assumption of array in framework getSubSettings

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#332]
We've come across a number of errors since using getSubSettings in the framework.
```
ExternalModules::array_merge_recursive_distinct()
```
ends up getting a string instead of an array in some use cases.  I think it might happen when an EM was activated on a project and then a future version of the EM added a subsetting to the config.json.  If you re-save the configuration for the EM with the new settings it will no longer throw the error, but if you have projects in your system with the older configuration it does.

```
The 'survey_ui_tweaks' module threw the following exception when calling the hook method 'redcap_every_page_top':

TypeError: Argument 2 passed to ExternalModules\ExternalModules::array_merge_recursive_distinct() must be of the type array, boolean given, called in /var/www/html/redcap_v9.9.1/ExternalModules/classes/framework/Framework.php on line 207 and defined in /var/www/html/redcap_v9.9.1/ExternalModules/classes/ExternalModules.php:5089
Stack trace:
#0 /var/www/html/redcap_v9.9.1/ExternalModules/classes/framework/Framework.php(207): ExternalModules\ExternalModules::array_merge_recursive_distinct(Array, true)
#1 /var/www/html/redcap_v9.9.1/ExternalModules/classes/framework/Framework.php(154): ExternalModules\Framework->getSubSettings_internal(Array, Array)
#2 /var/www/html/modules-lab/survey_ui_tweaks_v9.9.9/SurveyUITweaks.php(42): ExternalModules\Framework->getSubSettings('survey_tweaks')
#3 /var/www/html/modules-lab/survey_ui_tweaks_v9.9.9/SurveyUITweaks.php(82): Stanford\SurveyUITweaks\SurveyUITweaks->loadInstances()
#4 [internal function]: Stanford\SurveyUITweaks\SurveyUITweaks->redcap_every_page_top('4730')
#5 /var/www/html/redcap_v9.9.1/ExternalModules/classes/ExternalModules.php(2612): call_user_func_array(Array, Array)
#6 /var/www/html/redcap_v9.9.1/ExternalModules/classes/ExternalModules.php(2770): ExternalModules\ExternalModules::startHook('survey_ui_tweak...', 'v9.9.9', Array)
#7 /var/www/html/redcap_v9.9.1/ExternalModules/classes/ExternalModules.php(2790): ExternalModules\ExternalModules::ExternalModules\{closure}('survey_ui_tweak...', 'v9.9.9')
#8 /var/www/html/redcap_v9.9.1/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook('every_page_top', Array)
#9 /var/www/html/redcap_v9.9.1/Classes/HtmlPage.php(133): Hooks::call('redcap_every_pa...', Array)
#10 /var/www/html/redcap_v9.9.1/Views/HeaderProject.php(19): HtmlPage->PrintHeader(false)
#11 /var/www/html/redcap_v9.9.1/ProjectGeneral/header.php(6): require('/var/www/html/r...')
#12 /var/www/html/redcap_v9.9.1/ProjectSetup/index.php(13): include('/var/www/html/r...')
#13 {main}
```

**Comment by mmcev106** [comment]
I may need more specifics to help with this.  There are a lot of edge cases with subsettings, and the differences between the new and old implementations are subtle but can have significant consequences.  We've had to be very careful when transitioning modules from the old to new implementations.  Manually re-entering the settings on all projects might be the safest and least time consuming approach in some cases.

We have unit tests covering the edge cases we have identified so far.  I'm unclear if the above error is caused by a new edge case the framework can handle automatically, or if a transition process specific to this module's setting structure is needed.

**Comment by mmcev106** [comment]
I just updated the [v2 docs](https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/framework/v2.md) with a summary of our latest knowledge on this issue (similar to the above comment).  Please let me know (or submit a PR) if you think there's anything else we should say in the documentation for this breaking change.
