### ISSUE TITLE
DB Error: Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by pbchase** [vanderbilt/redcap-external-modules#91]
Two hours after we upgraded to REDCap 8.3.0 (from 8.2.0), we started getting errors from our REDCap system. The all flow out of the External Module code and all contain "DB Error: Lost connection to MySQL server during query". Here are two typical examples. 

```
REDCap External Modules threw the following exception:

exception 'Exception' with message 'Error running External Module query: 
DB Error: Lost connection to MySQL server during query
SQL: SELECT * 
FROM information_schema.COLUMNS 
WHERE 
TABLE_SCHEMA = 'ctsi_redcap' 
AND TABLE_NAME = 'redcap_external_module_settings' 
AND COLUMN_NAME = 'type'' in /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php:1091
Stack trace:
#0 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1585): ExternalModules\ExternalModules::query('SELECT * \r\n\t\t\tF...')
#1 [internal function]: ExternalModules\ExternalModules::isTypePresentInTable()
#2 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1624): ReflectionMethod->invokeArgs(NULL, Array)
#3 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1606): ExternalModules\ExternalModules::callPrivateMethod('isTypePresentIn...')
#4 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1532): ExternalModules\ExternalModules::getSqlToRunIfDBOutdated()
#5 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1439): ExternalModules\ExternalModules::cacheAllEnableData()
#6 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1429): ExternalModules\ExternalModules::getSystemwideEnabledVersions()
#7 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1251): ExternalModules\ExternalModules::getEnabledModules(NULL)
#8 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/Classes/Hooks.php(37): ExternalModules\ExternalModules::callHook('redcap_every_pa...', Array)
#9 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/Classes/System.php(475): Hooks::call('redcap_every_pa...')
#10 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/Config/init_global.php(9): System::initGlobalPage()
#11 /var/www.backup/redcap-20180322T2011/redcap_v8.3.0/ProjectGeneral/keep_alive.php(12): require_once('/var/www.backup...')
#12 {main}

URL: https://example.org/redcap/redcap_v8.3.0/ProjectGeneral/keep_alive.php
```

```
REDCap External Modules threw the following exception:

exception 'Exception' with message 'Error running External Module query: 
DB Error: Lost connection to MySQL server during query
SQL: SELECT * 
FROM information_schema.COLUMNS 
WHERE 
TABLE_SCHEMA = 'ctsi_redcap' 
AND TABLE_NAME = 'redcap_external_module_settings' 
AND COLUMN_NAME = 'type'' in /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php:1091
Stack trace:
#0 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1585): ExternalModules\ExternalModules::query('SELECT * \r\n\t\t\tF...')
#1 [internal function]: ExternalModules\ExternalModules::isTypePresentInTable()
#2 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1624): ReflectionMethod->invokeArgs(NULL, Array)
#3 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1606): ExternalModules\ExternalModules::callPrivateMethod('isTypePresentIn...')
#4 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1532): ExternalModules\ExternalModules::getSqlToRunIfDBOutdated()
#5 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1457): ExternalModules\ExternalModules::cacheAllEnableData()
#6 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1466): ExternalModules\ExternalModules::getProjectEnabledOverrides()
#7 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1432): ExternalModules\ExternalModules::getEnabledModuleVersionsForProject('4134')
#8 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/ExternalModules/classes/ExternalModules.php(1251): ExternalModules\ExternalModules::getEnabledModules('4134')
#9 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/Classes/Hooks.php(37): ExternalModules\ExternalModules::callHook('redcap_every_pa...', Array)
#10 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/Classes/System.php(584): Hooks::call('redcap_every_pa...', Array)
#11 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/Config/init_project.php(9): System::initProjectPage()
#12 /var/www.backup/redcap-20180323T0340/redcap_v8.3.0/Design/check_field_name.php(6): require_once('/var/www.backup...')
#13 {main}

URL: https://example.org/redcap/redcap_v8.3.0/Design/check_field_name.php?pid=4134&field_name=date_of_demo&old_field_name=
```

The server is behaving normally otherwise.  Any thoughts? 

Philip

**Comment by mmcev106** [comment]
I'm afraid I don't have any more information besides what's already in this post:

https://community.projectredcap.org/questions/36116/exception-from-redcap-external-modules-constantly.html

**Comment by pbchase** [comment]
@mmcev106, thanks for the link. That's a good read. I added my own commentary there. Perhaps the error was in the changes between 8.2.0 and 8.2.1?

**Comment by mmcev106** [comment]
Per [this comment](http://community.projectredcap.org/comments/40487/view.html), emails should no longer be sent in this scenario.  The error will still be displayed to users.  Feel free to re-open this if you have any other outstanding concerns.
